In [1]:
import pandas as pd
import numpy as np
import CococoNet_reader
import Name_resolver
import os
import itertools
import warnings
import pickle
import tqdm
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
favorite_color = pickle.load( open( "/data/passala/Post_dump_files/Generated_Tables/Comparing_all_orthogorups_across_plants/Orthogroup_based_coconets_null/rice_jp_merged_cococonet_pickle_null.p", "rb" ) )
favorite_color

,100263at3193,1004at3193,10054at3193,10077at3193,10091at3193,100974at3193,101191at3193,101256at3193,101302at3193,101354at3193,...,9828at3193,9836at3193,98658at3193,98920at3193,9917at3193,9919at3193,99231at3193,99342at3193,9959at3193,99917at3193
100263at3193,0.630704,0.695730,0.402338,0.281617,0.573488,0.271795,0.254144,0.542830,0.288335,0.339889,...,0.152595,0.113189,0.216120,0.253248,0.495429,0.368442,0.272504,0.495570,0.092943,0.343257
1004at3193,0.695730,1.000000,0.383615,0.787724,0.912311,0.669942,0.187638,0.735022,0.723649,0.648677,...,0.304074,0.166850,0.723650,0.732240,0.675927,0.482612,0.531422,0.811636,0.820760,0.583311
10054at3193,0.402338,0.383615,1.000000,0.909663,0.938200,0.541205,0.790576,0.922267,0.554945,0.795027,...,0.049631,0.807131,0.731631,0.930908,0.793079,0.209063,0.658922,0.783896,0.314077,0.659626
10077at3193,0.281617,0.787724,0.909663,1.000000,0.994411,0.915396,0.945737,0.797803,0.887377,0.967645,...,0.101790,0.879407,0.993388,0.980012,0.995436,0.075273,0.889385,0.956752,0.987592,0.912187
10091at3193,0.573488,0.912311,0.938200,0.994411,1.000000,0.920062,0.905408,0.913408,0.934483,0.946600,...,0.674996,0.722664,0.962595,0.980919,0.940955,0.087424,0.930824,0.983822,0.840487,0.923875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9919at3193,0.368442,0.482612,0.209063,0.075273,0.087424,0.198958,0.382295,0.509963,0.118794,0.051886,...,0.010376,0.079519,0.031178,0.332702,0.301250,1.000000,0.334586,0.037474,0.034253,0.270882
99231at3193,0.272504,0.531422,0.658922,0.889385,0.930824,0.684177,0.713214,0.798928,0.713556,0.938759,...,0.914300,0.035293,0.962620,0.783727,0.679782,0.334586,1.000000,0.982077,0.939989,0.814205
99342at3193,0.495570,0.811636,0.783896,0.956752,0.983822,0.646608,0.715296,0.800762,0.855479,0.990047,...,0.918866,0.512286,0.981631,0.907119,0.855739,0.037474,0.982077,1.000000,0.971814,0.895377
9959at3193,0.092943,0.820760,0.314077,0.987592,0.840487,0.730290,0.644766,0.368771,0.882528,0.908034,...,0.889320,0.789107,0.986393,0.841119,0.890697,0.034253,0.939989,0.971814,1.000000,0.812184
99917at3193,0.343257,0.583311,0.659626,0.912187,0.923875,0.628119,0.628066,0.589039,0.646903,0.882752,...,0.261175,0.663038,0.879375,0.904716,0.804970,0.270882,0.814205,0.895377,0.812184,0.640779

In [11]:

# common_name_1 = Name_resolver.species_name_resolver('rice_jp','common')
# common_name_2 = Name_resolver.species_name_resolver('apple','common')





# ## Read In Cococonets 
# coconet_species_one = coconet_1
# coconet_species_two = coconet_2







# #Identify Pairs for evaluation

# pairs_to_keep = list(set(coconet_species_one.index.to_list()) & set(coconet_species_two.index.to_list()))

# all_pairs_to_evaluate_for_functional_conservation = pd.DataFrame(columns = [f'{common_name_1} and {common_name_2}'],data= pairs_to_keep)


# all_pairs_to_evaluate_for_functional_conservation['Species 1 Score'] = np.nan
# all_pairs_to_evaluate_for_functional_conservation['Species 2 Score'] = np.nan


# ## Trim cococonets to match


# trimmed_species_1_cococonet = coconet_species_one[coconet_species_one.columns.intersection(pairs_to_keep)]
# trimmed_species_1_cococonet = trimmed_species_1_cococonet[trimmed_species_1_cococonet.index.isin(pairs_to_keep)]
# double_species_1_trimmed_cococonet = trimmed_species_1_cococonet.replace(1,0)

# trimmed_species_2_cococonet = coconet_species_two[coconet_species_two.columns.intersection(pairs_to_keep)]
# trimmed_species_2_cococonet = trimmed_species_2_cococonet[trimmed_species_2_cococonet.index.isin(pairs_to_keep)]
# double_species_2_trimmed_cococonet = trimmed_species_2_cococonet.replace(1,0)

In [21]:
# ## Rank
# species_1_cococonet_ranked = trimmed_species_1_cococonet.rank()
# species_2_cococonet_ranked = trimmed_species_2_cococonet.rank()

# #Do top 10 Genes
# top_10_species_1_genes = np.array(
#     [double_species_1_trimmed_cococonet.T[c].nlargest(10).index.values for c in double_species_1_trimmed_cococonet.T]
# )  # using pair list above, cut down top 10 list to relevant genes, probably by adding list as a column in panda and then filtering panda to index of pair list
# top_10_species_1_genes_dataframe = pd.DataFrame(
#     data=top_10_species_1_genes,
#     index=double_species_1_trimmed_cococonet.index,
#     columns=[
#         "One",
#         "Two",
#         "Three",
#         "Four",
#         "Five",
#         "Six",
#         "Seven",
#         "Eight",
#         "Nine",
#         "Ten",
#     ],
# )

# #Convert 
# top_10_species_1_genes_as_species_2 = top_10_species_1_genes_dataframe

# # Get genes for checking 
# have_species_1_pairs = all_pairs_to_evaluate_for_functional_conservation.loc[all_pairs_to_evaluate_for_functional_conservation[f'{common_name_1} and {common_name_2}'].isin(top_10_species_1_genes_as_species_2.index)]
# trimmed_all_gene_pairs_for_fc = have_species_1_pairs.loc[have_species_1_pairs[f'{common_name_1} and {common_name_2}'].isin(trimmed_species_2_cococonet.index)]
# trimmed_all_gene_pairs_for_fc = trimmed_all_gene_pairs_for_fc.reset_index(drop = True)

# # Get values in species 2 
# for two_genes in trimmed_all_gene_pairs_for_fc.iterrows():
#     current_species_1_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
#     current_species_2_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
#     finger_print_genes = top_10_species_1_genes_as_species_2.loc[current_species_1_gene].to_list()
#     gene_ranks_in_species_2 = species_2_cococonet_ranked.loc[species_2_cococonet_ranked.index.isin(finger_print_genes), current_species_2_gene]
#     avg_rank_in_species_2 = gene_ranks_in_species_2.mean()
#     index_from_pairs = two_genes[0]
#     trimmed_all_gene_pairs_for_fc.at[index_from_pairs, 'Species 1 Score'] = avg_rank_in_species_2

# #Repeat for Species 2 

# top_10_species_2_genes = np.array(
#     [double_species_2_trimmed_cococonet.T[c].nlargest(10).index.values for c in double_species_2_trimmed_cococonet.T]
# )  # using pair list above, cut down top 10 list to relevant genes, probably by adding list as a column in panda and then filtering panda to index of pair list
# top_10_species_2_genes_dataframe = pd.DataFrame(
#     data=top_10_species_2_genes,
#     index=double_species_2_trimmed_cococonet.index,
#     columns=[
#         "One",
#         "Two",
#         "Three",
#         "Four",
#         "Five",
#         "Six",
#         "Seven",
#         "Eight",
#         "Nine",
#         "Ten",
#     ],
# )


# #convert 
# top_10_species_2_genes_as_species_1 = top_10_species_2_genes_dataframe


# # Get values in species 1 
# for two_genes in trimmed_all_gene_pairs_for_fc.iterrows():
#     current_species_1_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
#     current_species_2_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
#     finger_print_genes = top_10_species_2_genes_as_species_1.loc[current_species_2_gene].to_list()
#     gene_ranks_in_species_1 = species_1_cococonet_ranked.loc[species_1_cococonet_ranked.index.isin(finger_print_genes), current_species_1_gene]
#     avg_rank_in_species_1 = gene_ranks_in_species_1.mean()
#     index_from_pairs = two_genes[0]
#     trimmed_all_gene_pairs_for_fc.loc[index_from_pairs, 'Species 2 Score'] = avg_rank_in_species_1

# #Caluclate Divisors 
# Number_of_species_1_genes = len(top_10_species_1_genes_as_species_2)
# Number_of_species_2_genes = len(top_10_species_2_genes_as_species_1)


# species_1_score_divisor = Number_of_species_2_genes - 4.5
# species_2_score_divisor = Number_of_species_1_genes-4.5

# #Divide and Average 
# trimmed_all_gene_pairs_for_fc['Species 1 Score'] = trimmed_all_gene_pairs_for_fc['Species 1 Score']/species_1_score_divisor
# trimmed_all_gene_pairs_for_fc['Species 2 Score'] = trimmed_all_gene_pairs_for_fc['Species 2 Score']/species_2_score_divisor
# trimmed_all_gene_pairs_for_fc['Total Score'] = trimmed_all_gene_pairs_for_fc[['Species 1 Score','Species 2 Score']].mean(axis = 1)

In [3]:
def Calculate_Score_list_for_thresholding(coconet_1, coconet_2, Species_1 = 'rice',Species_2 = 'maize', ):

    import pandas as pd
    import itertools

    common_name_1 = Name_resolver.species_name_resolver(Species_1,'common')
    common_name_2 = Name_resolver.species_name_resolver(Species_2,'common')





    ## Read In Cococonets 
    coconet_species_one = coconet_1
    coconet_species_two = coconet_2







    #Identify Pairs for evaluation

    pairs_to_keep = list(set(coconet_species_one.index.to_list()) & set(coconet_species_two.index.to_list()))

    all_pairs_to_evaluate_for_functional_conservation = pd.DataFrame(columns = [f'{common_name_1} and {common_name_2}'],data= pairs_to_keep)


    all_pairs_to_evaluate_for_functional_conservation['Species 1 Score'] = np.nan
    all_pairs_to_evaluate_for_functional_conservation['Species 2 Score'] = np.nan


    ## Trim cococonets to match


    trimmed_species_1_cococonet = coconet_species_one[coconet_species_one.columns.intersection(pairs_to_keep)]
    trimmed_species_1_cococonet = trimmed_species_1_cococonet[trimmed_species_1_cococonet.index.isin(pairs_to_keep)]
    double_species_1_trimmed_cococonet = trimmed_species_1_cococonet.replace(1,0)

    trimmed_species_2_cococonet = coconet_species_two[coconet_species_two.columns.intersection(pairs_to_keep)]
    trimmed_species_2_cococonet = trimmed_species_2_cococonet[trimmed_species_2_cococonet.index.isin(pairs_to_keep)]
    double_species_2_trimmed_cococonet = trimmed_species_2_cococonet.replace(1,0)



    ## Rank
    species_1_cococonet_ranked = trimmed_species_1_cococonet.rank()
    species_2_cococonet_ranked = trimmed_species_2_cococonet.rank()

    #Do top 10 Genes
    top_10_species_1_genes = np.array(
        [double_species_1_trimmed_cococonet.T[c].nlargest(10).index.values for c in double_species_1_trimmed_cococonet.T]
    )  # using pair list above, cut down top 10 list to relevant genes, probably by adding list as a column in panda and then filtering panda to index of pair list
    top_10_species_1_genes_dataframe = pd.DataFrame(
        data=top_10_species_1_genes,
        index=double_species_1_trimmed_cococonet.index,
        columns=[
            "One",
            "Two",
            "Three",
            "Four",
            "Five",
            "Six",
            "Seven",
            "Eight",
            "Nine",
            "Ten",
        ],
    )

    #Convert 
    top_10_species_1_genes_as_species_2 = top_10_species_1_genes_dataframe

    # Get genes for checking 
    have_species_1_pairs = all_pairs_to_evaluate_for_functional_conservation.loc[all_pairs_to_evaluate_for_functional_conservation[f'{common_name_1} and {common_name_2}'].isin(top_10_species_1_genes_as_species_2.index)]
    trimmed_all_gene_pairs_for_fc = have_species_1_pairs.loc[have_species_1_pairs[f'{common_name_1} and {common_name_2}'].isin(trimmed_species_2_cococonet.index)]
    trimmed_all_gene_pairs_for_fc = trimmed_all_gene_pairs_for_fc.reset_index(drop = True)

    # Get values in species 2 
    for two_genes in trimmed_all_gene_pairs_for_fc.iterrows():
        current_species_1_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
        current_species_2_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
        finger_print_genes = top_10_species_1_genes_as_species_2.loc[current_species_1_gene].to_list()
        gene_ranks_in_species_2 = species_2_cococonet_ranked.loc[species_2_cococonet_ranked.index.isin(finger_print_genes), current_species_2_gene]
        avg_rank_in_species_2 = gene_ranks_in_species_2.mean()
        index_from_pairs = two_genes[0]
        trimmed_all_gene_pairs_for_fc.at[index_from_pairs, 'Species 1 Score'] = avg_rank_in_species_2

    #Repeat for Species 2 

    top_10_species_2_genes = np.array(
        [double_species_2_trimmed_cococonet.T[c].nlargest(10).index.values for c in double_species_2_trimmed_cococonet.T]
    )  # using pair list above, cut down top 10 list to relevant genes, probably by adding list as a column in panda and then filtering panda to index of pair list
    top_10_species_2_genes_dataframe = pd.DataFrame(
        data=top_10_species_2_genes,
        index=double_species_2_trimmed_cococonet.index,
        columns=[
            "One",
            "Two",
            "Three",
            "Four",
            "Five",
            "Six",
            "Seven",
            "Eight",
            "Nine",
            "Ten",
        ],
    )


    #convert 
    top_10_species_2_genes_as_species_1 = top_10_species_2_genes_dataframe


    # Get values in species 1 
    for two_genes in trimmed_all_gene_pairs_for_fc.iterrows():
        current_species_1_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
        current_species_2_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
        finger_print_genes = top_10_species_2_genes_as_species_1.loc[current_species_2_gene].to_list()
        gene_ranks_in_species_1 = species_1_cococonet_ranked.loc[species_1_cococonet_ranked.index.isin(finger_print_genes), current_species_1_gene]
        avg_rank_in_species_1 = gene_ranks_in_species_1.mean()
        index_from_pairs = two_genes[0]
        trimmed_all_gene_pairs_for_fc.loc[index_from_pairs, 'Species 2 Score'] = avg_rank_in_species_1

    #Caluclate Divisors 
    Number_of_species_1_genes = len(top_10_species_1_genes_as_species_2)
    Number_of_species_2_genes = len(top_10_species_2_genes_as_species_1)


    species_1_score_divisor = Number_of_species_2_genes - 4.5
    species_2_score_divisor = Number_of_species_1_genes-4.5

    #Divide and Average 
    trimmed_all_gene_pairs_for_fc['Species 1 Score'] = trimmed_all_gene_pairs_for_fc['Species 1 Score']/species_1_score_divisor
    trimmed_all_gene_pairs_for_fc['Species 2 Score'] = trimmed_all_gene_pairs_for_fc['Species 2 Score']/species_2_score_divisor
    trimmed_all_gene_pairs_for_fc['Total Score'] = trimmed_all_gene_pairs_for_fc[['Species 1 Score','Species 2 Score']].mean(axis = 1)
        
    return trimmed_all_gene_pairs_for_fc

In [4]:
species_to_run_on = pd.read_csv('/data/passala/Generated_Tables/Reference_tables/species_for_running_cross_ortho_analysis.csv')

In [5]:
list_of_species_to_run_on = species_to_run_on['Common Name'].to_list()

In [6]:
all_coconets = {}
for species in tqdm.tqdm(list_of_species_to_run_on):
    current_net = pickle.load( open( f"/data/passala/Post_dump_files/Generated_Tables/Comparing_all_orthogorups_across_plants/Orthogroup_based_coconets_null/{species}_merged_cococonet_pickle_null.p", "rb" ) )
    all_coconets[species] = current_net

100%|██████████| 15/15 [00:48<00:00,  3.23s/it]

In [7]:
all_combos_to_run_on = list(itertools.combinations(list_of_species_to_run_on,2))

In [8]:
len(all_combos_to_run_on)

105

In [9]:
generated_files = os.listdir('/data/passala/Post_dump_files/Generated_Tables/Comparing_all_orthogorups_across_plants/1_1_ortho_FC_tables_null')

In [10]:
len(generated_files)

0

In [11]:
for combo in tqdm.tqdm(all_combos_to_run_on):
    species_1 = combo[0]
    species_2 = combo[1]
    coconet_spec_1 = all_coconets[species_1]
    coconet_spec_2 = all_coconets[species_2]
    
    score_list = Calculate_Score_list_for_thresholding(coconet_1=coconet_spec_1, coconet_2= coconet_spec_2, Species_1= species_1, Species_2= species_2)
    score_list.to_csv(f'/data/passala/Post_dump_files/Generated_Tables/Comparing_all_orthogorups_across_plants/1_1_ortho_FC_tables_null/{species_1}_{species_2}_NM_null.csv')

100%|██████████| 105/105 [1:57:40<00:00, 67.24s/it]