In [1]:
import pandas as pd
import numpy as np
import CococoNet_reader
import Name_resolver
import os
import itertools
import warnings
import pickle
import tqdm
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
favorite_color = pickle.load( open( "/data/passala/Generated_Tables/Comparing_all_orthogorups_across_plants/Orthogroup_based_coconets/rice_jp_merged_cococonet_pickle.p", "rb" ) )
favorite_color

,100263at3193,1004at3193,10051at3193,10055at3193,10092at3193,10107at3193,101191at3193,101302at3193,1013at3193,10147at3193,...,9822at3193,9828at3193,98658at3193,9877at3193,98920at3193,9919at3193,99342at3193,9942at3193,9959at3193,99917at3193
100263at3193,1.000000,0.729381,0.504292,0.737027,0.394877,0.319333,0.358613,0.614028,0.381168,0.210326,...,0.323415,0.698730,0.738675,0.568793,0.798469,0.728366,0.809183,0.599391,0.311896,0.556057
1004at3193,0.729381,1.000000,0.239033,0.764126,0.312704,0.165585,0.430423,0.614028,0.150997,0.711709,...,0.237226,0.947418,0.919683,0.982755,0.887158,0.859930,0.469182,0.731139,0.828082,0.627385
10051at3193,0.504292,0.239033,1.000000,0.264421,0.375120,0.167220,0.464333,0.614028,0.523854,0.783733,...,0.439099,0.280724,0.298612,0.467748,0.184736,0.694508,0.489142,0.190125,0.320317,0.443172
10055at3193,0.737027,0.764126,0.264421,1.000000,0.952534,0.037850,0.354840,0.614028,0.144005,0.896704,...,0.214513,0.956849,0.883705,0.874310,0.405196,0.970301,0.388845,0.746128,0.839952,0.358146
10092at3193,0.394877,0.312704,0.375120,0.952534,1.000000,0.246135,0.482239,0.614028,0.403727,0.989375,...,0.144259,0.929755,0.804748,0.888018,0.118678,0.979050,0.366288,0.898691,0.974040,0.459563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9919at3193,0.728366,0.859930,0.694508,0.970301,0.979050,0.230490,0.477829,0.614028,0.347025,0.986356,...,0.373338,0.958615,0.766902,0.908537,0.056865,1.000000,0.758253,0.823540,0.991604,0.575680
99342at3193,0.809183,0.469182,0.489142,0.388845,0.366288,0.811469,0.480275,0.614028,0.809083,0.245132,...,0.263740,0.396955,0.006290,0.682698,0.673172,0.758253,1.000000,0.636027,0.780065,0.518266
9942at3193,0.599391,0.731139,0.190125,0.746128,0.898691,0.455874,0.469579,0.614028,0.521190,0.679436,...,0.136428,0.832992,0.778517,0.904077,0.610591,0.823540,0.636027,0.841920,0.812579,0.510462
9959at3193,0.311896,0.828082,0.320317,0.839952,0.974040,0.548958,0.480797,0.614028,0.827415,0.991730,...,0.212403,0.800271,0.562091,0.931433,0.438433,0.991604,0.780065,0.812579,1.000000,0.607116
99917at3193,0.556057,0.627385,0.443172,0.358146,0.459563,0.389796,0.497124,0.614028,0.531440,0.622517,...,0.456244,0.472594,0.369571,0.622733,0.459873,0.575680,0.518266,0.510462,0.607116,0.737641

In [11]:

# common_name_1 = Name_resolver.species_name_resolver('rice_jp','common')
# common_name_2 = Name_resolver.species_name_resolver('apple','common')





# ## Read In Cococonets 
# coconet_species_one = coconet_1
# coconet_species_two = coconet_2







# #Identify Pairs for evaluation

# pairs_to_keep = list(set(coconet_species_one.index.to_list()) & set(coconet_species_two.index.to_list()))

# all_pairs_to_evaluate_for_functional_conservation = pd.DataFrame(columns = [f'{common_name_1} and {common_name_2}'],data= pairs_to_keep)


# all_pairs_to_evaluate_for_functional_conservation['Species 1 Score'] = np.nan
# all_pairs_to_evaluate_for_functional_conservation['Species 2 Score'] = np.nan


# ## Trim cococonets to match


# trimmed_species_1_cococonet = coconet_species_one[coconet_species_one.columns.intersection(pairs_to_keep)]
# trimmed_species_1_cococonet = trimmed_species_1_cococonet[trimmed_species_1_cococonet.index.isin(pairs_to_keep)]
# double_species_1_trimmed_cococonet = trimmed_species_1_cococonet.replace(1,0)

# trimmed_species_2_cococonet = coconet_species_two[coconet_species_two.columns.intersection(pairs_to_keep)]
# trimmed_species_2_cococonet = trimmed_species_2_cococonet[trimmed_species_2_cococonet.index.isin(pairs_to_keep)]
# double_species_2_trimmed_cococonet = trimmed_species_2_cococonet.replace(1,0)

In [21]:
# ## Rank
# species_1_cococonet_ranked = trimmed_species_1_cococonet.rank()
# species_2_cococonet_ranked = trimmed_species_2_cococonet.rank()

# #Do top 10 Genes
# top_10_species_1_genes = np.array(
#     [double_species_1_trimmed_cococonet.T[c].nlargest(10).index.values for c in double_species_1_trimmed_cococonet.T]
# )  # using pair list above, cut down top 10 list to relevant genes, probably by adding list as a column in panda and then filtering panda to index of pair list
# top_10_species_1_genes_dataframe = pd.DataFrame(
#     data=top_10_species_1_genes,
#     index=double_species_1_trimmed_cococonet.index,
#     columns=[
#         "One",
#         "Two",
#         "Three",
#         "Four",
#         "Five",
#         "Six",
#         "Seven",
#         "Eight",
#         "Nine",
#         "Ten",
#     ],
# )

# #Convert 
# top_10_species_1_genes_as_species_2 = top_10_species_1_genes_dataframe

# # Get genes for checking 
# have_species_1_pairs = all_pairs_to_evaluate_for_functional_conservation.loc[all_pairs_to_evaluate_for_functional_conservation[f'{common_name_1} and {common_name_2}'].isin(top_10_species_1_genes_as_species_2.index)]
# trimmed_all_gene_pairs_for_fc = have_species_1_pairs.loc[have_species_1_pairs[f'{common_name_1} and {common_name_2}'].isin(trimmed_species_2_cococonet.index)]
# trimmed_all_gene_pairs_for_fc = trimmed_all_gene_pairs_for_fc.reset_index(drop = True)

# # Get values in species 2 
# for two_genes in trimmed_all_gene_pairs_for_fc.iterrows():
#     current_species_1_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
#     current_species_2_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
#     finger_print_genes = top_10_species_1_genes_as_species_2.loc[current_species_1_gene].to_list()
#     gene_ranks_in_species_2 = species_2_cococonet_ranked.loc[species_2_cococonet_ranked.index.isin(finger_print_genes), current_species_2_gene]
#     avg_rank_in_species_2 = gene_ranks_in_species_2.mean()
#     index_from_pairs = two_genes[0]
#     trimmed_all_gene_pairs_for_fc.at[index_from_pairs, 'Species 1 Score'] = avg_rank_in_species_2

# #Repeat for Species 2 

# top_10_species_2_genes = np.array(
#     [double_species_2_trimmed_cococonet.T[c].nlargest(10).index.values for c in double_species_2_trimmed_cococonet.T]
# )  # using pair list above, cut down top 10 list to relevant genes, probably by adding list as a column in panda and then filtering panda to index of pair list
# top_10_species_2_genes_dataframe = pd.DataFrame(
#     data=top_10_species_2_genes,
#     index=double_species_2_trimmed_cococonet.index,
#     columns=[
#         "One",
#         "Two",
#         "Three",
#         "Four",
#         "Five",
#         "Six",
#         "Seven",
#         "Eight",
#         "Nine",
#         "Ten",
#     ],
# )


# #convert 
# top_10_species_2_genes_as_species_1 = top_10_species_2_genes_dataframe


# # Get values in species 1 
# for two_genes in trimmed_all_gene_pairs_for_fc.iterrows():
#     current_species_1_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
#     current_species_2_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
#     finger_print_genes = top_10_species_2_genes_as_species_1.loc[current_species_2_gene].to_list()
#     gene_ranks_in_species_1 = species_1_cococonet_ranked.loc[species_1_cococonet_ranked.index.isin(finger_print_genes), current_species_1_gene]
#     avg_rank_in_species_1 = gene_ranks_in_species_1.mean()
#     index_from_pairs = two_genes[0]
#     trimmed_all_gene_pairs_for_fc.loc[index_from_pairs, 'Species 2 Score'] = avg_rank_in_species_1

# #Caluclate Divisors 
# Number_of_species_1_genes = len(top_10_species_1_genes_as_species_2)
# Number_of_species_2_genes = len(top_10_species_2_genes_as_species_1)


# species_1_score_divisor = Number_of_species_2_genes - 4.5
# species_2_score_divisor = Number_of_species_1_genes-4.5

# #Divide and Average 
# trimmed_all_gene_pairs_for_fc['Species 1 Score'] = trimmed_all_gene_pairs_for_fc['Species 1 Score']/species_1_score_divisor
# trimmed_all_gene_pairs_for_fc['Species 2 Score'] = trimmed_all_gene_pairs_for_fc['Species 2 Score']/species_2_score_divisor
# trimmed_all_gene_pairs_for_fc['Total Score'] = trimmed_all_gene_pairs_for_fc[['Species 1 Score','Species 2 Score']].mean(axis = 1)

In [12]:
def Calculate_Score_list_for_thresholding(coconet_1, coconet_2, Species_1 = 'rice',Species_2 = 'maize', ):

    import pandas as pd
    import itertools

    common_name_1 = Name_resolver.species_name_resolver(Species_1,'common')
    common_name_2 = Name_resolver.species_name_resolver(Species_2,'common')





    ## Read In Cococonets 
    coconet_species_one = coconet_1
    coconet_species_two = coconet_2







    #Identify Pairs for evaluation

    pairs_to_keep = list(set(coconet_species_one.index.to_list()) & set(coconet_species_two.index.to_list()))

    all_pairs_to_evaluate_for_functional_conservation = pd.DataFrame(columns = [f'{common_name_1} and {common_name_2}'],data= pairs_to_keep)


    all_pairs_to_evaluate_for_functional_conservation['Species 1 Score'] = np.nan
    all_pairs_to_evaluate_for_functional_conservation['Species 2 Score'] = np.nan


    ## Trim cococonets to match


    trimmed_species_1_cococonet = coconet_species_one[coconet_species_one.columns.intersection(pairs_to_keep)]
    trimmed_species_1_cococonet = trimmed_species_1_cococonet[trimmed_species_1_cococonet.index.isin(pairs_to_keep)]
    double_species_1_trimmed_cococonet = trimmed_species_1_cococonet.replace(1,0)

    trimmed_species_2_cococonet = coconet_species_two[coconet_species_two.columns.intersection(pairs_to_keep)]
    trimmed_species_2_cococonet = trimmed_species_2_cococonet[trimmed_species_2_cococonet.index.isin(pairs_to_keep)]
    double_species_2_trimmed_cococonet = trimmed_species_2_cococonet.replace(1,0)



    ## Rank
    species_1_cococonet_ranked = trimmed_species_1_cococonet.rank()
    species_2_cococonet_ranked = trimmed_species_2_cococonet.rank()

    #Do top 10 Genes
    top_10_species_1_genes = np.array(
        [double_species_1_trimmed_cococonet.T[c].nlargest(10).index.values for c in double_species_1_trimmed_cococonet.T]
    )  # using pair list above, cut down top 10 list to relevant genes, probably by adding list as a column in panda and then filtering panda to index of pair list
    top_10_species_1_genes_dataframe = pd.DataFrame(
        data=top_10_species_1_genes,
        index=double_species_1_trimmed_cococonet.index,
        columns=[
            "One",
            "Two",
            "Three",
            "Four",
            "Five",
            "Six",
            "Seven",
            "Eight",
            "Nine",
            "Ten",
        ],
    )

    #Convert 
    top_10_species_1_genes_as_species_2 = top_10_species_1_genes_dataframe

    # Get genes for checking 
    have_species_1_pairs = all_pairs_to_evaluate_for_functional_conservation.loc[all_pairs_to_evaluate_for_functional_conservation[f'{common_name_1} and {common_name_2}'].isin(top_10_species_1_genes_as_species_2.index)]
    trimmed_all_gene_pairs_for_fc = have_species_1_pairs.loc[have_species_1_pairs[f'{common_name_1} and {common_name_2}'].isin(trimmed_species_2_cococonet.index)]
    trimmed_all_gene_pairs_for_fc = trimmed_all_gene_pairs_for_fc.reset_index(drop = True)

    # Get values in species 2 
    for two_genes in trimmed_all_gene_pairs_for_fc.iterrows():
        current_species_1_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
        current_species_2_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
        finger_print_genes = top_10_species_1_genes_as_species_2.loc[current_species_1_gene].to_list()
        gene_ranks_in_species_2 = species_2_cococonet_ranked.loc[species_2_cococonet_ranked.index.isin(finger_print_genes), current_species_2_gene]
        avg_rank_in_species_2 = gene_ranks_in_species_2.mean()
        index_from_pairs = two_genes[0]
        trimmed_all_gene_pairs_for_fc.at[index_from_pairs, 'Species 1 Score'] = avg_rank_in_species_2

    #Repeat for Species 2 

    top_10_species_2_genes = np.array(
        [double_species_2_trimmed_cococonet.T[c].nlargest(10).index.values for c in double_species_2_trimmed_cococonet.T]
    )  # using pair list above, cut down top 10 list to relevant genes, probably by adding list as a column in panda and then filtering panda to index of pair list
    top_10_species_2_genes_dataframe = pd.DataFrame(
        data=top_10_species_2_genes,
        index=double_species_2_trimmed_cococonet.index,
        columns=[
            "One",
            "Two",
            "Three",
            "Four",
            "Five",
            "Six",
            "Seven",
            "Eight",
            "Nine",
            "Ten",
        ],
    )


    #convert 
    top_10_species_2_genes_as_species_1 = top_10_species_2_genes_dataframe


    # Get values in species 1 
    for two_genes in trimmed_all_gene_pairs_for_fc.iterrows():
        current_species_1_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
        current_species_2_gene = two_genes[1][f'{common_name_1} and {common_name_2}']
        finger_print_genes = top_10_species_2_genes_as_species_1.loc[current_species_2_gene].to_list()
        gene_ranks_in_species_1 = species_1_cococonet_ranked.loc[species_1_cococonet_ranked.index.isin(finger_print_genes), current_species_1_gene]
        avg_rank_in_species_1 = gene_ranks_in_species_1.mean()
        index_from_pairs = two_genes[0]
        trimmed_all_gene_pairs_for_fc.loc[index_from_pairs, 'Species 2 Score'] = avg_rank_in_species_1

    #Caluclate Divisors 
    Number_of_species_1_genes = len(top_10_species_1_genes_as_species_2)
    Number_of_species_2_genes = len(top_10_species_2_genes_as_species_1)


    species_1_score_divisor = Number_of_species_2_genes - 4.5
    species_2_score_divisor = Number_of_species_1_genes-4.5

    #Divide and Average 
    trimmed_all_gene_pairs_for_fc['Species 1 Score'] = trimmed_all_gene_pairs_for_fc['Species 1 Score']/species_1_score_divisor
    trimmed_all_gene_pairs_for_fc['Species 2 Score'] = trimmed_all_gene_pairs_for_fc['Species 2 Score']/species_2_score_divisor
    trimmed_all_gene_pairs_for_fc['Total Score'] = trimmed_all_gene_pairs_for_fc[['Species 1 Score','Species 2 Score']].mean(axis = 1)
        
    return trimmed_all_gene_pairs_for_fc

In [4]:
species_to_run_on = pd.read_csv('/data/passala/Generated_Tables/Reference_tables/species_for_running_cross_ortho_analysis.csv')

In [5]:
list_of_species_to_run_on = species_to_run_on['Common Name'].to_list()

In [6]:
all_coconets = {}
for species in tqdm.tqdm(list_of_species_to_run_on):
    current_net = pickle.load( open( f"/data/passala/Generated_Tables/Comparing_all_orthogorups_across_plants/Orthogroup_based_coconets/{species}_merged_cococonet_pickle.p", "rb" ) )
    all_coconets[species] = current_net

100%|██████████| 15/15 [00:05<00:00,  2.78it/s]

In [7]:
all_combos_to_run_on = list(itertools.combinations(list_of_species_to_run_on,2))

In [8]:
len(all_combos_to_run_on)

105

In [10]:
generated_files = os.listdir('/data/passala/Generated_Tables/Comparing_all_orthogorups_across_plants/1_1_ortho_FC_tables')

In [10]:
len(generated_files)

105

In [13]:
for combo in tqdm.tqdm(all_combos_to_run_on):
    species_1 = combo[0]
    species_2 = combo[1]
    coconet_spec_1 = all_coconets[species_1]
    coconet_spec_2 = all_coconets[species_2]
    
    score_list = Calculate_Score_list_for_thresholding(coconet_1=coconet_spec_1, coconet_2= coconet_spec_2, Species_1= species_1, Species_2= species_2)
    score_list.to_csv(f'/data/passala/Generated_Tables/Comparing_all_orthogorups_across_plants/1_1_ortho_FC_tables/{species_1}_{species_2}_NM.csv')

100%|██████████| 105/105 [1:45:58<00:00, 60.56s/it]