In [27]:
import pandas as pd 
import GO_Enrichment_Calculator
import Go_annotations

In [3]:
all_fc_scores = pd.read_csv('/data/passala/Generated_Tables/Comparing_all_orthogorups_across_plants/Ortho_fc_scores_full_table/avg_of_one_species_v_all.csv', index_col= 0 )
all_fc_scores

,rice_jp,apple,sorghum,maize,grape,mustard,soybean,medicago,tobacco,potato,tomato,arabidopsis,peanut,cucumber,brome
10009at3193,NaN,NaN,NaN,NaN,0.602391,NaN,0.635981,0.476311,0.566935,0.515122,0.557878,0.584060,0.633060,NaN,NaN
10051at3193,0.681775,NaN,0.614371,0.576558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10092at3193,0.783370,0.635207,0.805819,0.841827,0.851494,0.702748,0.822412,0.780372,0.829440,0.797876,0.850557,0.789432,0.809780,0.778494,0.805058
10147at3193,0.843007,0.854666,0.894450,NaN,0.839483,0.905545,0.876293,0.871565,0.889439,0.903582,0.880065,0.786749,0.866370,0.894824,0.898700
1018at3193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9842at3193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9877at3193,0.873297,0.884347,0.898559,NaN,0.890571,0.868611,0.899667,0.883150,0.870148,0.854566,0.842350,0.878853,0.877166,0.851742,0.884567
9919at3193,0.973417,0.969235,0.982164,0.983412,0.972806,0.985135,0.978850,0.984651,0.981008,0.976979,0.981237,0.972704,0.978750,0.979013,0.969112
9942at3193,0.788257,0.744464,0.807753,0.811668,0.776771,0.856961,0.831713,0.865782,0.816318,0.854899,0.754348,0.870898,0.841105,0.863090,0.793066
9959at3193,0.963818,NaN,0.982616,0.974048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.991942

In [11]:
all_fc_scores_sufficient_groups = all_fc_scores.dropna(thresh= 4)

In [12]:
all_fc_scores_sufficient_groups

,rice_jp,apple,sorghum,maize,grape,mustard,soybean,medicago,tobacco,potato,tomato,arabidopsis,peanut,cucumber,brome
10009at3193,NaN,NaN,NaN,NaN,0.602391,NaN,0.635981,0.476311,0.566935,0.515122,0.557878,0.584060,0.633060,NaN,NaN
10092at3193,0.783370,0.635207,0.805819,0.841827,0.851494,0.702748,0.822412,0.780372,0.829440,0.797876,0.850557,0.789432,0.809780,0.778494,0.805058
10147at3193,0.843007,0.854666,0.894450,NaN,0.839483,0.905545,0.876293,0.871565,0.889439,0.903582,0.880065,0.786749,0.866370,0.894824,0.898700
10228at3193,0.927451,0.867244,0.938266,NaN,0.928270,0.935168,0.908888,0.945870,0.949014,0.924221,0.932981,0.952850,0.922081,0.925227,0.932854
10238at3193,0.774580,0.761862,0.721842,NaN,0.741484,NaN,0.716873,NaN,0.678572,NaN,0.735944,0.763396,0.735738,0.786804,0.737348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9836at3193,NaN,0.772331,0.751485,0.794451,0.740404,0.783793,0.736784,0.762135,0.770175,0.742211,0.826177,0.772516,0.775074,0.624292,NaN
9877at3193,0.873297,0.884347,0.898559,NaN,0.890571,0.868611,0.899667,0.883150,0.870148,0.854566,0.842350,0.878853,0.877166,0.851742,0.884567
9919at3193,0.973417,0.969235,0.982164,0.983412,0.972806,0.985135,0.978850,0.984651,0.981008,0.976979,0.981237,0.972704,0.978750,0.979013,0.969112
9942at3193,0.788257,0.744464,0.807753,0.811668,0.776771,0.856961,0.831713,0.865782,0.816318,0.854899,0.754348,0.870898,0.841105,0.863090,0.793066
9959at3193,0.963818,NaN,0.982616,0.974048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.991942

In [85]:
all_fc_scores_sufficient_groups_high_mean = all_fc_scores_sufficient_groups.loc[all_fc_scores_sufficient_groups.mean(axis =1)>.8]
all_fc_scores_sufficient_groups_high_mean

,rice_jp,apple,sorghum,maize,grape,mustard,soybean,medicago,tobacco,potato,tomato,arabidopsis,peanut,cucumber,brome
10147at3193,0.843007,0.854666,0.894450,NaN,0.839483,0.905545,0.876293,0.871565,0.889439,0.903582,0.880065,0.786749,0.866370,0.894824,0.898700
10228at3193,0.927451,0.867244,0.938266,NaN,0.928270,0.935168,0.908888,0.945870,0.949014,0.924221,0.932981,0.952850,0.922081,0.925227,0.932854
10488at3193,NaN,0.953107,0.951542,0.942264,0.911984,0.952416,0.943870,0.940935,0.955328,0.950808,0.949593,0.948038,0.808213,0.957050,0.929444
10582at3193,0.909961,0.839009,0.909297,0.899394,0.889555,0.789605,0.876892,0.875223,0.922033,0.913685,0.873886,0.914496,0.914159,0.885128,0.908019
10648at3193,0.929343,0.952737,0.943984,0.957766,0.932169,0.920339,0.948837,0.949055,0.950296,0.910100,0.942147,0.941662,0.946337,0.947012,0.952785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9828at3193,0.767354,0.808910,0.828835,NaN,0.854239,0.862185,0.847868,0.851390,0.858946,0.773328,0.826891,0.850433,0.824053,0.847464,0.834174
9877at3193,0.873297,0.884347,0.898559,NaN,0.890571,0.868611,0.899667,0.883150,0.870148,0.854566,0.842350,0.878853,0.877166,0.851742,0.884567
9919at3193,0.973417,0.969235,0.982164,0.983412,0.972806,0.985135,0.978850,0.984651,0.981008,0.976979,0.981237,0.972704,0.978750,0.979013,0.969112
9942at3193,0.788257,0.744464,0.807753,0.811668,0.776771,0.856961,0.831713,0.865782,0.816318,0.854899,0.754348,0.870898,0.841105,0.863090,0.793066
9959at3193,0.963818,NaN,0.982616,0.974048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.991942

In [86]:
one_messed_up = all_fc_scores_sufficient_groups_high_mean.loc[all_fc_scores_sufficient_groups_high_mean.min(axis = 1)<.5]

In [87]:
one_messed_up

,rice_jp,apple,sorghum,maize,grape,mustard,soybean,medicago,tobacco,potato,tomato,arabidopsis,peanut,cucumber,brome
123537at3193,0.889446,0.891173,0.900834,NaN,0.904321,0.893511,0.891608,0.886515,0.914756,0.908053,0.902820,0.874197,0.433182,0.899996,0.780032
127336at3193,0.907362,0.911944,0.928720,0.446336,0.909322,0.890411,0.919232,0.907983,0.917504,0.925654,0.922564,0.913739,0.758554,0.925283,0.922840
128620at3193,0.874550,0.873609,0.637467,0.388512,0.872544,0.886425,0.899352,0.870198,0.891128,0.894590,0.895673,0.899111,0.883391,0.877098,0.890590
130690at3193,0.374682,0.851980,0.856357,0.846163,0.854365,0.817290,0.838500,0.864594,0.887775,0.870614,0.870820,0.875178,0.828728,0.816503,0.843731
132318at3193,0.477012,0.845020,0.892331,NaN,0.862820,0.755722,0.847777,0.862334,0.889254,0.870574,0.880872,0.887308,0.875538,NaN,0.789181
132464at3193,0.469194,0.873570,0.845304,0.854893,0.857924,0.886578,0.796615,0.887689,0.882332,0.864683,0.893532,0.861245,0.878924,0.874561,0.853416
133902at3193,NaN,NaN,0.929067,NaN,0.917740,NaN,0.921017,0.913941,0.900247,0.909895,0.926577,0.929936,0.434832,0.934982,NaN
17077at3193,0.893721,0.882197,0.875541,NaN,0.920686,0.878135,0.488960,0.879463,0.922301,0.936195,0.913944,0.919710,0.888380,0.908235,0.930726
204109at3193,0.865357,0.810777,0.928041,0.919900,0.889958,0.922207,0.927077,0.920802,0.922837,0.440213,0.924381,0.926344,0.904055,0.922694,NaN
25685at3193,NaN,NaN,0.850294,0.866846,0.854164,NaN,0.834609,0.855782,0.829370,0.460351,0.866323,0.884132,NaN,0.895820,NaN
282466at3193,0.479655,0.795946,0.899843,0.831025,0.828349,0.892928,0.875619,0.875892,0.885384,0.895820,0.896099,0.891658,0.880652,0.864735,0.876135
329708at3193,0.475959,0.845740,0.815369,NaN,0.791607,0.812073,0.826918,0.828222,0.856464,0.859067,0.873372,0.829838,0.849899,0.810897,0.771479
361398at3193,0.779773,0.848378,NaN,0.699739,0.887713,0.880883,0.854913,0.868227,0.885449,0.879135,0.883550,0.859574,0.432097,0.891425,NaN
3837at3193,0.480151,0.863142,0.871289,0.865738,0.855161,0.850555,0.885208,0.862665,0.880706,0.864038,0.905128,0.899209,0.889635,0.879632,0.876330
398745at3193,0.764680,0.875370,0.847664,0.496511,0.862165,0.752910,0.837915,0.857590,0.843724,0.870165,0.866435,0.853047,0.861437,0.849621,0.864233
42076at3193,0.839186,NaN,0.870579,0.834970,0.862348,0.745255,0.875629,0.867729,0.701377,0.880051,0.896153,0.865523,0.499931,0.855058,0.854232
43789at3193,NaN,NaN,0.904841,0.900777,0.919848,0.909154,0.897927,0.909990,0.267014,0.903168,0.925047,0.910707,NaN,0.904971,NaN
502at3193,0.916468,0.935707,0.937192,0.918938,0.928501,0.931408,0.938423,0.933140,0.938119,0.930041,0.931399,0.942878,0.330039,0.927973,0.931772
53318at3193,0.487538,0.819742,0.841294,NaN,0.851300,0.854788,0.832309,0.875337,0.869184,0.856245,0.875113,0.834205,0.770893,0.784361,0.830807
56463at3193,0.819155,0.824610,0.832541,0.497635,0.857454,0.803934,0.853651,0.857724,0.856258,0.870924,0.836795,0.833233,0.824947,0.846772,0.811802
649557at3193,NaN,0.877892,0.857083,NaN,0.838645,0.851762,0.869531,0.422091,0.868120,0.879503,0.865632,0.861867,0.745552,0.837314,0.856171
746233at3193,0.886681,0.911532,0.890601,0.914257,0.823537,0.910890,0.897195,0.893518,0.910437,0.863227,0.914840,0.898359,0.488623,0.913586,0.874777
75292at3193,NaN,0.843568,0.874700,0.838752,0.863617,0.861589,0.870246,0.868451,0.873460,0.858397,0.864410,0.868424,0.417340,0.829291,0.854988
754906at3193,0.757930,0.852573,0.860751,0.803862,0.855053,0.876998,0.876967,0.447072,0.872225,0.842821,0.847911,0.881222,0.848053,0.843751,0.874277
768717at3193,NaN,0.910414,0.939960,0.492207,0.926654,0.925449,0.930432,0.932082,0.936110,0.942630,0.929567,0.920862,0.934906,0.924720,0.920703
799037at3193,NaN,0.765695,0.872388,0.873393,0.882056,0.495154,0.860616,0.787054,0.853166,0.848525,0.888696,0.849053,0.691346,0.891460,NaN
80800at3193,0.840357,0.876778,0.871761,0.830568,0.826898,0.876704,0.718526,0.885688,0.468679,0.860127,0.807287,0.856801,0.858975,0.882106,0.880182
873831at3193,NaN,0.834320,0.868068,0.870884,0.844585,0.677891,0.838482,NaN,0.880277,0.855214,0.871758,0.487968,0.777459,0.870575,0.878797
877420at3193,0.916985,0.916410,0.923795,0.921963,0.878682,0.940484,0.922664,0.256200,0.924912,0.930434,0.924674,0.927142,0.928166,0.922919,0.933108
880862at3193,0.750316,0.461907,NaN,0.850590,0.861134,0.884699,0.811347,0.619995,NaN,0.880970,0.876861,0.851840,NaN,0.880022,0.905024
881784at3193,0.495692,0.870548,0.843576,0.865011,0.845392,NaN,0.858661,0.902599,NaN,0.904101,0.916421,0.876266,NaN,0.862713,NaN
882259at3193,0.871278,0.881941,0.857618,0.882005,0.899658,0.900849,0.879372,0.899228,0.895744,0.867556,NaN,0.907550,0.893903,0.886770,0.486703
883597at3193,NaN,0.919601,0.942607,0.913947,0.925192,0.926624,0.917773,0.915654,0.936931,0.926916,NaN,0.925675,0.489156,0.924456,0.923306
885543at3193,0.425134,0.831006,0.872364,NaN,0.849899,0.869139,0.837764,0.783627,0.868826,0.865759,0.863705,0.838886,0.864072,0.870128,0.842105
886517at3193,NaN,0.389004,0.938231,NaN,0.936157,0.931308,0.934925,0.938129,0.924515,0.914869,0.937062,0.933253,0.904728,0.921237,NaN
887454at3193,0.396525,0.843451,0.824575,0.780340,0.840342,0.845280,0.846003,0.862219,0.860586,0.861474,0.850428,0.848749,0.854634,0.861939,NaN
890073at3193,0.240532,NaN,0.846271,0.906719,0.898522,0.901071,0.902486,0.908617,0.900066,0.902545,0.909788,0.905922,NaN,0.902196,NaN

In [88]:
one_messed_up_with_arabi = one_messed_up.dropna(subset='arabidopsis')
one_messed_up_with_arabi

,rice_jp,apple,sorghum,maize,grape,mustard,soybean,medicago,tobacco,potato,tomato,arabidopsis,peanut,cucumber,brome
123537at3193,0.889446,0.891173,0.900834,NaN,0.904321,0.893511,0.891608,0.886515,0.914756,0.908053,0.902820,0.874197,0.433182,0.899996,0.780032
127336at3193,0.907362,0.911944,0.928720,0.446336,0.909322,0.890411,0.919232,0.907983,0.917504,0.925654,0.922564,0.913739,0.758554,0.925283,0.922840
128620at3193,0.874550,0.873609,0.637467,0.388512,0.872544,0.886425,0.899352,0.870198,0.891128,0.894590,0.895673,0.899111,0.883391,0.877098,0.890590
130690at3193,0.374682,0.851980,0.856357,0.846163,0.854365,0.817290,0.838500,0.864594,0.887775,0.870614,0.870820,0.875178,0.828728,0.816503,0.843731
132318at3193,0.477012,0.845020,0.892331,NaN,0.862820,0.755722,0.847777,0.862334,0.889254,0.870574,0.880872,0.887308,0.875538,NaN,0.789181
132464at3193,0.469194,0.873570,0.845304,0.854893,0.857924,0.886578,0.796615,0.887689,0.882332,0.864683,0.893532,0.861245,0.878924,0.874561,0.853416
133902at3193,NaN,NaN,0.929067,NaN,0.917740,NaN,0.921017,0.913941,0.900247,0.909895,0.926577,0.929936,0.434832,0.934982,NaN
17077at3193,0.893721,0.882197,0.875541,NaN,0.920686,0.878135,0.488960,0.879463,0.922301,0.936195,0.913944,0.919710,0.888380,0.908235,0.930726
204109at3193,0.865357,0.810777,0.928041,0.919900,0.889958,0.922207,0.927077,0.920802,0.922837,0.440213,0.924381,0.926344,0.904055,0.922694,NaN
25685at3193,NaN,NaN,0.850294,0.866846,0.854164,NaN,0.834609,0.855782,0.829370,0.460351,0.866323,0.884132,NaN,0.895820,NaN
282466at3193,0.479655,0.795946,0.899843,0.831025,0.828349,0.892928,0.875619,0.875892,0.885384,0.895820,0.896099,0.891658,0.880652,0.864735,0.876135
329708at3193,0.475959,0.845740,0.815369,NaN,0.791607,0.812073,0.826918,0.828222,0.856464,0.859067,0.873372,0.829838,0.849899,0.810897,0.771479
361398at3193,0.779773,0.848378,NaN,0.699739,0.887713,0.880883,0.854913,0.868227,0.885449,0.879135,0.883550,0.859574,0.432097,0.891425,NaN
3837at3193,0.480151,0.863142,0.871289,0.865738,0.855161,0.850555,0.885208,0.862665,0.880706,0.864038,0.905128,0.899209,0.889635,0.879632,0.876330
398745at3193,0.764680,0.875370,0.847664,0.496511,0.862165,0.752910,0.837915,0.857590,0.843724,0.870165,0.866435,0.853047,0.861437,0.849621,0.864233
42076at3193,0.839186,NaN,0.870579,0.834970,0.862348,0.745255,0.875629,0.867729,0.701377,0.880051,0.896153,0.865523,0.499931,0.855058,0.854232
43789at3193,NaN,NaN,0.904841,0.900777,0.919848,0.909154,0.897927,0.909990,0.267014,0.903168,0.925047,0.910707,NaN,0.904971,NaN
502at3193,0.916468,0.935707,0.937192,0.918938,0.928501,0.931408,0.938423,0.933140,0.938119,0.930041,0.931399,0.942878,0.330039,0.927973,0.931772
53318at3193,0.487538,0.819742,0.841294,NaN,0.851300,0.854788,0.832309,0.875337,0.869184,0.856245,0.875113,0.834205,0.770893,0.784361,0.830807
56463at3193,0.819155,0.824610,0.832541,0.497635,0.857454,0.803934,0.853651,0.857724,0.856258,0.870924,0.836795,0.833233,0.824947,0.846772,0.811802
649557at3193,NaN,0.877892,0.857083,NaN,0.838645,0.851762,0.869531,0.422091,0.868120,0.879503,0.865632,0.861867,0.745552,0.837314,0.856171
746233at3193,0.886681,0.911532,0.890601,0.914257,0.823537,0.910890,0.897195,0.893518,0.910437,0.863227,0.914840,0.898359,0.488623,0.913586,0.874777
75292at3193,NaN,0.843568,0.874700,0.838752,0.863617,0.861589,0.870246,0.868451,0.873460,0.858397,0.864410,0.868424,0.417340,0.829291,0.854988
754906at3193,0.757930,0.852573,0.860751,0.803862,0.855053,0.876998,0.876967,0.447072,0.872225,0.842821,0.847911,0.881222,0.848053,0.843751,0.874277
768717at3193,NaN,0.910414,0.939960,0.492207,0.926654,0.925449,0.930432,0.932082,0.936110,0.942630,0.929567,0.920862,0.934906,0.924720,0.920703
799037at3193,NaN,0.765695,0.872388,0.873393,0.882056,0.495154,0.860616,0.787054,0.853166,0.848525,0.888696,0.849053,0.691346,0.891460,NaN
80800at3193,0.840357,0.876778,0.871761,0.830568,0.826898,0.876704,0.718526,0.885688,0.468679,0.860127,0.807287,0.856801,0.858975,0.882106,0.880182
873831at3193,NaN,0.834320,0.868068,0.870884,0.844585,0.677891,0.838482,NaN,0.880277,0.855214,0.871758,0.487968,0.777459,0.870575,0.878797
877420at3193,0.916985,0.916410,0.923795,0.921963,0.878682,0.940484,0.922664,0.256200,0.924912,0.930434,0.924674,0.927142,0.928166,0.922919,0.933108
880862at3193,0.750316,0.461907,NaN,0.850590,0.861134,0.884699,0.811347,0.619995,NaN,0.880970,0.876861,0.851840,NaN,0.880022,0.905024
881784at3193,0.495692,0.870548,0.843576,0.865011,0.845392,NaN,0.858661,0.902599,NaN,0.904101,0.916421,0.876266,NaN,0.862713,NaN
882259at3193,0.871278,0.881941,0.857618,0.882005,0.899658,0.900849,0.879372,0.899228,0.895744,0.867556,NaN,0.907550,0.893903,0.886770,0.486703
883597at3193,NaN,0.919601,0.942607,0.913947,0.925192,0.926624,0.917773,0.915654,0.936931,0.926916,NaN,0.925675,0.489156,0.924456,0.923306
885543at3193,0.425134,0.831006,0.872364,NaN,0.849899,0.869139,0.837764,0.783627,0.868826,0.865759,0.863705,0.838886,0.864072,0.870128,0.842105
886517at3193,NaN,0.389004,0.938231,NaN,0.936157,0.931308,0.934925,0.938129,0.924515,0.914869,0.937062,0.933253,0.904728,0.921237,NaN
887454at3193,0.396525,0.843451,0.824575,0.780340,0.840342,0.845280,0.846003,0.862219,0.860586,0.861474,0.850428,0.848749,0.854634,0.861939,NaN
890073at3193,0.240532,NaN,0.846271,0.906719,0.898522,0.901071,0.902486,0.908617,0.900066,0.902545,0.909788,0.905922,NaN,0.902196,NaN

In [89]:
ortho_to_gene = pd.read_csv('/data/passala/OrthoDB_data/NCBI_data/og_2_Genes_with_network_id.csv')
ortho_to_gene

,Orthogroup,Gene,Species,Ortholevel,Orthodb Gene,Symbol
0,100007at3193,4558_0:003a4f,4558,3193,4558_0:003a4f,LOC110434333
1,100007at3193,4577_0:004254,4577,3193,4577_0:004254,Zm00001d017285
2,100007at3193,4577_0:004e43,4577,3193,4577_0:004e43,LOC100275058
3,100067at3193,4558_0:00439a,4558,3193,4558_0:00439a,LOC8071983
4,100085at3193,4558_0:002fd8,4558,3193,4558_0:002fd8,LOC8086335
...,...,...,...,...,...,...
502887,9969at3193,15368_0:000e9a,15368,3193,15368_0:000e9a,LOC100834561
502888,99917at3193,39947_0:006297,39947,3193,39947_0:006297,Os11g0656400
502889,99917at3193,39947_0:00634f,39947,3193,39947_0:00634f,Os11g0656000
502890,99917at3193,39947_0:006629,39947,3193,39947_0:006629,Os11g0656700
502891,99999at3193,39947_0:006fc4,39947,3193,39947_0:006fc4,orf173

In [90]:
arabi_genes = ortho_to_gene.loc[ortho_to_gene['Orthogroup'].isin(one_messed_up_with_arabi.index) ]
arabi_genes

,Orthogroup,Gene,Species,Ortholevel,Orthodb Gene,Symbol
40727,123537at3193,15368_0:003821,15368,3193,15368_0:003821,LOC100829825
40728,123537at3193,29760_0:005565,29760,3193,29760_0:005565,LOC100267745
40729,123537at3193,3659_0:000d54,3659,3193,3659_0:000d54,LOC101220081
40730,123537at3193,3702_0:00033d,3702,3193,3702_0:00033d,AT1G07700
40731,123537at3193,3711_0:002dcd,3711,3193,3711_0:002dcd,LOC103861485
...,...,...,...,...,...,...
491460,890073at3193,4558_0:00327c,4558,3193,4558_0:00327c,LOC8085182
491461,890073at3193,4558_0:0034e0,4558,3193,4558_0:0034e0,LOC110434311
491462,890073at3193,4577_0:001074,4577,3193,4577_0:001074,Zm00001d034702
491463,890073at3193,4577_0:00324c,4577,3193,4577_0:00324c,Zm00001d051544
491464,890073at3193,4577_0:004a25,4577,3193,4577_0:004a25,Zm00001d017718

In [91]:
arabi_genes_to_species = arabi_genes.loc[arabi_genes['Species'] == 3702 ]
arabi_genes_to_species

,Orthogroup,Gene,Species,Ortholevel,Orthodb Gene,Symbol
40730,123537at3193,3702_0:00033d,3702,3193,3702_0:00033d,AT1G07700
53505,127336at3193,3702_0:003132,3702,3193,3702_0:003132,AT3G14930
57844,128620at3193,3702_0:00059a,3702,3193,3702_0:00059a,AT1G80380
64002,130690at3193,3702_0:005577,3702,3193,3702_0:005577,AT5G08110
69483,132318at3193,3702_0:004cfe,3702,3193,3702_0:004cfe,AT4G19900
...,...,...,...,...,...,...
472651,887454at3193,3702_0:001742,3702,3193,3702_0:001742,AT1G53300
472652,887454at3193,3702_0:0021f3,3702,3193,3702_0:0021f3,AT2G42580
472653,887454at3193,3702_0:003edb,3702,3193,3702_0:003edb,AT3G58620
491438,890073at3193,3702_0:003b8d,3702,3193,3702_0:003b8d,AT3G03130
491439,890073at3193,3702_0:005acd,3702,3193,3702_0:005acd,AT5G17160

In [92]:
list_of_arabidopsis_genes = arabi_genes_to_species['Symbol'].to_list()

In [93]:
arabi_annotations  = Go_annotations.get_go_annotations_as_panda('arabidopsis')

In [94]:
tables = GO_Enrichment_Calculator.generate_contigency_tables(go_annotations= arabi_annotations, gene_list= list_of_arabidopsis_genes)

In [95]:
fishers_results = GO_Enrichment_Calculator.fishers_exact_on_contigency_tables(tables, arabi_annotations)
fishers_results

             P_value
GO_term
GO:0000002  1.000000
GO:0000003  0.434716
GO:0000009  1.000000
GO:0000012  1.000000
GO:0000014  1.000000
...              ...
GO:2001280  1.000000
GO:2001289  1.000000
GO:2001293  1.000000
GO:2001294  1.000000
GO:2001295  1.000000

[10704 rows x 1 columns]

In [96]:
fishers_results.sort_values(by = 'P_value').head(20)

                 P_value
GO_term
GO:0016984  1.095347e-10
GO:0009853  4.707137e-09
GO:0043094  9.448884e-08
GO:0019253  1.276695e-07
GO:0019685  1.557813e-07
GO:0015977  3.162669e-07
GO:0016831  6.531699e-07
GO:0090116  8.641400e-07
GO:0003886  8.641400e-07
GO:0009008  1.232530e-06
GO:0010424  2.923597e-06
GO:0030621  4.836394e-06
GO:0008909  4.836394e-06
GO:0016830  6.859650e-06
GO:0010218  8.510698e-06
GO:0032776  1.152498e-05
GO:0010216  1.152498e-05
GO:0009544  1.448841e-05
GO:0050162  1.448841e-05
GO:0050486  1.448841e-05

In [97]:
final_results = GO_Enrichment_Calculator.multi_hypothesis_correct_fishers_exact(fishers_results)
final_results

            P_value
GO_term
GO:0000002      1.0
GO:0000003      1.0
GO:0000009      1.0
GO:0000012      1.0
GO:0000014      1.0
...             ...
GO:2001280      1.0
GO:2001289      1.0
GO:2001293      1.0
GO:2001294      1.0
GO:2001295      1.0

[10704 rows x 1 columns]

In [98]:
final_results.sort_values(by = 'P_value').head(20)

             P_value
GO_term
GO:0016984  0.000001
GO:0009853  0.000025
GO:0019253  0.000333
GO:0043094  0.000333
GO:0019685  0.000333
GO:0015977  0.000564
GO:0016831  0.000999
GO:0090116  0.001028
GO:0003886  0.001028
GO:0009008  0.001319
GO:0010424  0.002845
GO:0030621  0.003982
GO:0008909  0.003982
GO:0016830  0.005245
GO:0010218  0.006073
GO:0032776  0.007257
GO:0010216  0.007257
GO:0050162  0.007754
GO:0009544  0.007754
GO:0050486  0.007754

In [99]:
all_go_terms = pd.read_csv('/home/passala/Gene_duplication_project/Data_from_others/go_terms.txt',sep = '\t')

In [100]:
named_go = final_results.merge(right = all_go_terms, left_index=True, right_index= True)

In [101]:
named_go.sort_values(by = 'P_value').head(60)

             P_value                                               Name
GO:0016984  0.000001         ribulose-bisphosphate carboxylase activity
GO:0009853  0.000025                                   photorespiration
GO:0019685  0.000333                      photosynthesis, dark reaction
GO:0043094  0.000333                cellular metabolic compound salvage
GO:0019253  0.000333                  reductive pentose-phosphate cycle
GO:0015977  0.000564                                    carbon fixation
GO:0016831  0.000999                             carboxy-lyase activity
GO:0003886  0.001028       DNA (cytosine-5-)-methyltransferase activity
GO:0090116  0.001028                        C-5 methylation of cytosine
GO:0009008  0.001319                     DNA-methyltransferase activity
GO:0010424  0.002845   DNA methylation on cytosine within a CG sequence
GO:0030621  0.003982                                   U4 snRNA binding
GO:0008909  0.003982                    isochorismate synthase activity
GO:0016830  0.005245                       carbon-carbon lyase activity
GO:0010218  0.006073                          response to far red light
GO:0032776  0.007257                        DNA methylation on cytosine
GO:0010216  0.007257                     maintenance of DNA methylation
GO:0009544  0.007754                   chloroplast ATP synthase complex
GO:0050486  0.007754  intramolecular transferase activity, transferr...
GO:0050162  0.007754                           oxalate oxidase activity
GO:0051276  0.010966                            chromosome organization
GO:0010114  0.012153                              response to red light
GO:0034090  0.013466   maintenance of meiotic sister chromatid cohesion
GO:0009570  0.028289                                 chloroplast stroma
GO:0006259  0.028289                              DNA metabolic process
GO:0009532  0.028289                                     plastid stroma
GO:0034086  0.028289           maintenance of sister chromatid cohesion
GO:0006305  0.031989                                     DNA alkylation
GO:0006306  0.031989                                    DNA methylation
GO:0009637  0.034640                             response to blue light
GO:0031975  0.034640                                           envelope
GO:0110102  0.034640  ribulose bisphosphate carboxylase complex asse...
GO:0031967  0.034640                                 organelle envelope
GO:0009697  0.039920                salicylic acid biosynthetic process
GO:0010847  0.039920                   regulation of chromatin assembly
GO:0001672  0.049867    regulation of chromatin assembly or disassembly
GO:0051607  0.050114                          defense response to virus
GO:0009941  0.051179                               chloroplast envelope
GO:0042374  0.051179                    phylloquinone metabolic process
GO:0042372  0.051179                 phylloquinone biosynthetic process
GO:0000275  0.051179  mitochondrial proton-transporting ATP synthase...
GO:0017070  0.051179                                   U6 snRNA binding
GO:0043486  0.051179                                   histone exchange
GO:0016623  0.051179  oxidoreductase activity, acting on the aldehyd...
GO:0009526  0.054463                                   plastid envelope
GO:0044728  0.057151                   DNA methylation or demethylation
GO:0015979  0.062796                                     photosynthesis
GO:0043231  0.063155           intracellular membrane-bounded organelle
GO:0006304  0.066150                                   DNA modification
GO:0140097  0.082726                  catalytic activity, acting on DNA
GO:0045454  0.082726                             cell redox homeostasis
GO:0043227  0.085923                         membrane-bounded organelle
GO:0002252  0.093092                            immune effector process
GO:0045261  0.103883  proton-transporting ATP synthase complex, cata...
GO:0051177  0.103883                  meiotic sister chromatid cohesion
GO:0045144  0.103883               meiotic sister chromatid segregation
GO:0043229  0.103883                            intracellular organelle
GO:0098800  0.103883       inner mitochondrial membrane protein complex
GO:0046658  0.108942              anchored component of plasma membrane
GO:0043226  0.116127                                          organelle